name: CI para C

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositorio
        uses: actions/checkout@v3

      - name: Instalar compilador GCC
        run: sudo apt update && sudo apt install build-essential -y

      - name: Compilar o programa
        run: gcc math.c -o math_compilado

      - name: Executar o programa
        run: ./programa

      - name: Executar testes automatizados
        run: |
          gcc -o teste teste.c
          ./teste